openapi: 3.0.3
info:
  title: OpenAPI schema for GKE template .
components:
  schemas:
    variables:
      type: object
      properties:
        project_id:
          title: Project Id
          type: string
          description: The project ID to host the cluster in (required)
          default: ""
          x-walrus-ui:
            group: Basic
            order: 1
        name:
          title: Name
          type: string
          description: The name of the cluster (required)
          default: gke-cluster-
          x-walrus-ui:
            group: Basic
            order: 2
        region:
          title: Region
          type: string
          description: The region to host the cluster in (optional if zonal cluster
            / required if regional)
          x-walrus-ui:
            group: Basic
            order: 3
        zones:
          title: Zones
          type: array
          description: The zones to host the cluster in (optional if regional cluster
            / required if zonal)
          default: []
          items:
            type: string
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 4
        network:
          title: Network
          type: string
          description: The VPC network to host the cluster in (required).
          default: ""
          x-walrus-ui:
            group: Basic
            order: 5
        subnetwork:
          title: Subnetwork
          type: string
          description: The subnetwork to host the cluster in (required).
          default: ""
          x-walrus-ui:
            group: Basic
            order: 6
        ip_range_pods:
          title: Ip Range Pods
          type: string
          description: The _name_ of the secondary subnet ip range to use for pods
          default: 10.0.0.0/16
          x-walrus-ui:
            group: Basic
            order: 7
        ip_range_services:
          title: Ip Range Services
          type: string
          description: The _name_ of the secondary subnet range to use for services
          default: 10.10.0.0/16
          x-walrus-ui:
            group: Basic
            order: 8
        http_load_balancing:
          title: Http Load Balancing
          type: boolean
          description: Enable httpload balancer addon
          default: true
          enum:
          - true
          - false
          x-walrus-ui:
            group: Basic
            order: 9
        network_policy:
          title: Network Policy
          type: boolean
          description: Enable network policy addon
          default: false
          enum:
          - true
          - false
          x-walrus-ui:
            group: Basic
            order: 10
        horizontal_pod_autoscaling:
          title: Horizontal Pod Autoscaling
          type: boolean
          description: Enable or disable horizontal pod autoscaling.
          default: true
          enum:
          - true
          - false
          x-walrus-ui:
            group: Basic
            order: 11
        filestore_csi_driver:
          title: Filestore Csi Driver
          type: boolean
          description: The status of the Filestore CSI driver addon, which allows
            the usage of filestore instance as volumes
          default: false
          enum:
          - true
          - false
          x-walrus-ui:
            group: Basic
            order: 12
        dns_cache:
          title: Dns Cache
          type: boolean
          description: The status of the NodeLocal DNSCache addon.
          default: false
          enum:
          - true
          - false
          x-walrus-ui:
            group: Basic
            order: 13
        node_pools:
          title: Node Pools
          type: array
          description: List of maps containing node pools
          default:
          - accelerator_count: 1
            accelerator_type: nvidia-l4
            auto_repair: true
            auto_upgrade: true
            disk_size_gb: 100
            disk_type: pd-standard
            enable_gcfs: false
            enable_gvnic: false
            gpu_driver_version: LATEST
            gpu_sharing_strategy: TIME_SHARING
            image_type: COS_CONTAINERD
            initial_node_count: 80
            local_ssd_count: 0
            logging_variant: DEFAULT
            machine_type: e2-medium
            max_count: 100
            max_shared_clients_per_gpu: 2
            min_count: 1
            name: default-node-pool
            node_locations: us-central1-b,us-central1-c
            preemptible: false
            service_account: project-service-account@<PROJECT ID>.iam.gserviceaccount.com
            spot: false
          items:
            additionalProperties:
              type: object
              x-walrus-ui:
                colSpan: 12
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 14
            widget: YamlEditor
        node_pools_oauth_scopes:
          title: Node Pools Oauth Scopes
          type: object
          description: Map of lists containing node oauth scopes by node-pool name
          default:
            all:
            - https://www.googleapis.com/auth/cloud-platform
            default-node-pool: []
          additionalProperties:
            items:
              type: string
            type: array
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 15
        node_pools_labels:
          title: Node Pools Labels
          type: object
          description: Map of maps containing node labels by node-pool name
          default:
            all: {}
            default-node-pool: {}
          additionalProperties:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 16
        node_pools_metadata:
          title: Node Pools Metadata
          type: object
          description: Map of maps containing node metadata by node-pool name
          default:
            all: {}
            default-node-pool: {}
          additionalProperties:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 17
        node_pools_taints:
          title: Node Pools Taints
          type: object
          description: Map of lists containing node taints by node-pool name
          default:
            all: []
            default-node-pool: []
          additionalProperties:
            items:
              properties:
                effect:
                  title: Effect
                  type: string
                  x-walrus-ui:
                    order: 3
                key:
                  title: Key
                  type: string
                  x-walrus-ui:
                    order: 1
                value:
                  title: Value
                  type: string
                  x-walrus-ui:
                    order: 2
              required:
              - effect
              - key
              - value
              type: object
              x-walrus-ui:
                colSpan: 12
            type: array
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 18
        node_pools_tags:
          title: Node Pools Tags
          type: object
          description: Map of lists containing node network tags by node-pool name
          default:
            all: []
            default-node-pool: []
          additionalProperties:
            items:
              type: string
            type: array
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 19
      x-walrus-ui:
        groupOrder:
        - Basic
