openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      properties:
        name:
          title: Name
          type: string
          description: The name of the cluster (required)
          default: gke-cluster-
          x-walrus-ui:
            group: Basic
            order: 1
        region:
          title: Region
          type: string
          description: The region to host the cluster in (optional if zonal cluster
            / required if regional)
          x-walrus-ui:
            group: Basic
            order: 2
        access_type:
          title: Access Type
          type: string
          description: The VPC network to host the cluster in (required).
          default: INTERNAL
          enum:
          - INTERNAL
          - EXTERNAL
          x-walrus-ui:
            group: Basic
            order: 3
        subnetwork:
          title: Subnetwork
          type: string
          description: The subnetwork to host the cluster in (required).
          default: 10.0.0.0/16
          x-walrus-ui:
            group: Basic
            order: 4
        ip_range_pods:
          title: Ip Range Pods
          type: string
          description: The _name_ of the secondary subnet ip range to use for pods
          default: 192.168.0.0/24
          x-walrus-ui:
            group: Basic
            order: 5
        ip_range_services:
          title: Ip Range Services
          type: string
          description: The _name_ of the secondary subnet range to use for services
          default: 192.168.1.0/24
          x-walrus-ui:
            group: Basic
            order: 6
      x-walrus-ui:
        groupOrder:
        - Basic
